PR for New Sandbox
anthive/website pull request #217
Opened 2020-11-01 16:27 UTC by EgoriusRus

2020-11-02 08:48 UTC, kezlya reviewed
nado ydalit' anthive-4.0.js

2020-11-02 11:14 UTC, kezlya approved these changes
LGTM

2020-11-02 12:36 UTC, Klimonov commented on pages/sandbox/_lang.vue
> +          this.$router.push({ path: this.$route.path, query: { box: this.gameId } })
Если так или иначе мы перебрасываем пользователя на url игры, возможно, есть смысл делать это в finally ?

2020-11-02 12:36 UTC, Klimonov commented on pages/sandbox/_lang.vue
> +              if (passedTime === maxTime) {
Используй `>=`. Если вдруг кому то понадобится изменить интервал, ему нужно будет учитывать maxTime. А если он забудет, то всё, infinity loop

2020-11-02 12:36 UTC, Klimonov commented on pages/sandbox/_lang.vue
> +    async getGame() {
Метод написан сложно и требует времени для понимания, если ты это понимаешь, но нет идей как его упростить, пиши комментарии, хоть на каждой строке, если понадобится.

2020-11-02 15:34 UTC, kezlya requested changes
Merge this only when Design is ready

2020-11-02 15:57 UTC, Klimonov approved these changes
LGTM

2020-11-06 07:42 UTC, kezlya approved these changes
LGTM

2020-11-06 07:42 UTC, merged