PR for Games page
anthive/website pull request #66
Opened 2020-05-30 20:26 UTC by EgoriusRus

2020-06-01 06:00 UTC, Klimonov commented on services/Bot.js
> +  const q = query(sort, page, size, filter)
Именуй информативней

2020-06-01 06:00 UTC, Klimonov commented on components/gamesTable.vue
> +              v-if="(column.hasOwnProperty('sort')) &amp;&amp; column.sort =='desc'"
Зачем тут ` &amp;&amp;`

2020-06-01 09:04 UTC, kezlya requested changes
LGTM just need to address commments

2020-06-02 06:02 UTC, kezlya approved these changes
Thank you

2020-06-02 06:46 UTC, Klimonov commented on components/AntHiveBtn.vue
> +    :class="{'white--text': fill, 'primary--text': !fill & !primary,  }"
Должно быть два `&`

2020-06-02 07:45 UTC, Klimonov approved these changes
LGTM

2020-06-02 09:59 UTC, merged